#! /usr/bin/env python3

l_limit=4
print_line=0
file="announce.txt"
dumpfile=file+".dump"
ofile=open(dumpfile,"wb")

with open(file,"rb") as fin:
 for num,line in enumerate(fin):
  print_line+=1
  if num < print_line:
   if len(line) > l_limit:	
    print(line)
    ofile.write(line)
  else:
   exit("at line print limit")
exit()
